language: node_js
node_js:
  - "stable"	
sudo: required
services:
  - mongodb



branches:
  only:
    - master  

install:
  - npm install
  - npm install mongodb
  - npm install mongoose
  - npm install nodemon
  - npm install joi
  - npm install validator

script:
  - npm build

env:
  - SERVER_IP_ADDRESS=3.17.150.160

before_deploy:
  - chmod 400 testaws.pem
  - eval "$(ssh-agent -s)"
  

deploy:
  provider: script
  skip_cleanup: true
  script: "deploy.sh"
  on:
    branch: master
